# This is a basic workflow to help you get started with Actions

name: Terraform CICD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  T_VERSION: 1.2.8

  # Allows you to run this workflow manually from the Actions tab
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  terraform:
    name: 'Terraform cicd'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3


      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
          
      - name: Install Terraform
        uses: little-core-labs/install-terraform@v2.0.0
        with:
          version: ${T_VERSION}
      
      - name: show terraform version
        run: terraform version
    
      - uses: terraform-linters/setup-tflint@v2
        name: Setup TFLint
        with:
          tflint_version: latest

      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint -f compact

      

      - name: terraform init
        run: |
          cd single-linux-vm-k8s-userdata
          terraform init
      
      - name: create ssh keys
        run: | 
          cd single-linux-vm-k8s-userdata
          ssh-keygen -q -t rsa -N '' -f vm_key <<<y >/dev/null 2>&1
        
      - name: terraform plan
        run:  |
          cd single-linux-vm-k8s-userdata
          terraform plan
